FROM debian:12.7
WORKDIR /usr/local/TRE

RUN apt-get update && apt-get upgrade -y && \
apt-get install -y build-essential autotools-dev libtool gettext wget \
libgtk-3-dev libpulse-dev libpng-dev autoconf git \
g++-mingw-w64 gcc-mingw-w64 mingw-w64-tools cmake autopoint

RUN cd /usr/local/TRE && git clone https://github.com/laurikari/tre.git
RUN cd /usr/local/TRE/tre && git checkout 6092368aabdd0dbb0fbceb2766a37b98e0ff6911
RUN cd /usr/local/TRE/tre && ./utils/autogen.sh 
RUN cd /usr/local/TRE/tre && ./configure && make && make install
