FROM xroar/tre:12.7
WORKDIR /usr/local/SDL
COPY ./SDL /usr/local/SDL

RUN cd /usr/local/SDL && \
    cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=build-scripts/cmake-toolchain-mingw64-x86_64.cmake && \
    cmake --build build && \
    cmake --install build
