FROM xroar/tre:12.7
WORKDIR /usr/local/SDL

RUN apt-get update && apt-get upgrade -y 
RUN apt-get install -y build-essential git make \
pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev \
libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev \
libpipewire-0.3-dev libwayland-dev libdecor-0-dev git

RUN cd /usr/local/SDL && git clone https://github.com/libsdl-org/SDL.git

RUN cd /usr/local/SDL/SDL && ls -la
RUN cd /usr/local/SDL/SDL && \
    ./configure && make
