FROM xroar/tre:12.7
WORKDIR /usr/local/SDL
COPY ./SDL /usr/local/SDL

RUN apt-get install -y build-essential libgtk-3-dev libpulse-dev libpng-dev autoconf \
    g++-mingw-w64 gcc-mingw-w64 mingw-w64-tools cmake

RUN cd /usr/local/SDL && \
    cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=build-scripts/cmake-toolchain-mingw64-x86_64.cmake && \
    cmake --build build && \
    cmake --install build
